config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :genders
  resources :savings
  resources :incomes
  resources :frequencies
  root to: 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Sidekiq::Web => '/sidekiq'

  get 'search', to: 'search#search'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, path: 'accounts'

  resources :users do
    resources :profiles, only: %i[show edit update]
  end

  resources :budgets do
    resources :expenses
  end
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id              :integer          not null, primary key
#  phone           :string
#  dob             :date
#  city            :string
#  country         :string
#  address         :string
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  gender_id       :integer
#  image_data      :text
#  first_name      :string
#  middle_name     :string
#  last_name       :string
#  has_profile_pic :boolean          default(FALSE)
#
# Indexes
#
#  index_profiles_on_gender_id  (gender_id)
#  index_profiles_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (gender_id => genders.id)
#  fk_rails_...  (user_id => users.id)
#

class Profile < ApplicationRecord
    include ImageUploader::Attachment.new(:image) # adds an `image` virtual attribute

    ##
    # Relationships
    #
    belongs_to :user
    belongs_to :gender

    ##
    # Callbacks
    #
    before_commit :check_and_set_image, on: [:create, :update]

    ##
    # Validations
    #
    validates :first_name, presence: true
    

    def display_name
        self.first_name || self.last_name || self.middle_name
    end

    def full_name
        name = self.first_name
        name += " #{self.middle_name}" if self.middle_name.present?
        name += " #{self.last_name}" if self.last_name.present?
    end

    def city_and_country
        city_country = ''
        if self.city.present? && self.country.present?
            city_country = "#{self.city}, #{self.country}"
        elsif self.city.present?
            city_country = self.city
        elsif self.country.present?
            city_country = self.country
        end
        city_country
    end

    private
    def check_and_set_image
        if !self.image.present?
            self.has_profile_pic = false
            self.image = File.open(Rails.root + 'app/assets/images/' + ['default.png'].compact.join('_'))
        else
            self.has_profile_pic = true
        end
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :set_profile_of_current_user

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to user_profile_url(current_user, @profile), notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def profile_params
      params.require(:profile).permit(:first_name, :middle_name, :last_name, :phone, :dob, :city, :country, :address, :gender_id, :image, :remove_image)
    end

    def set_profile_of_current_user
      if user_signed_in?
        if profile=current_user.profile
          @profile = profile
        else
          redirect_to new_user_profile_path
        end
      else
        redirect_to new_user_session_url
      end
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
.row
  .col-lg-2
  .col-lg-8
    .row
      = form_with(model: [current_user, profile], local: true) do |form|
        - if profile.errors.any?
          #error_explanation
            %h3
              = pluralize(profile.errors.count, 'error')
              prohibited from being saved.
        .col-lg-5
          .right_aligned
            - if profile.image.present?
              = image_tag profile.image[:large_thumb].url, class: 'img-thumbnail'
              - if profile.has_profile_pic
                .checkbox
                  = form.label :remove_image do
                    = form.check_box :remove_image
                    Remove photo
            = form.hidden_field :image, value: form.object.cached_image_data
            = form.file_field :image, id: :profile_image, class: 'btn btn-primary btn-md btn-block'
            = form.error_message_for(:image)
        .col-lg-7
          .form-group
            = form.label :first_name
            = form.text_field :first_name, id: :profile_first_name, class: 'form-control', autofocus: true
            = form.error_message_for(:first_name)
          .form-group
            = form.label :middle_name
            = form.text_field :middle_name, id: :profile_middle_name, class: 'form-control'
            = form.error_message_for(:middle_name)
          .form-group
            = form.label :last_name
            = form.text_field :last_name, id: :profile_last_name, class: 'form-control'
            = form.error_message_for(:last_name)
          .form-group
            = form.label :phone
            = form.text_field :phone, id: :profile_phone, class: 'form-control'
            = form.error_message_for(:phone)
          .form-group
            = form.label :dob
            = form.date_select :dob, start_year: 1980, id: :profile_dob, class: 'form-control'
            = form.error_message_for(:dob)
          .form-group
            = form.label :city
            = form.text_field :city, id: :profile_city, class: 'form-control'
            = form.error_message_for(:city)
          .form-group
            = form.label :country
            = form.text_field :country, id: :profile_country, class: 'form-control'
            = form.error_message_for(:country)
          .form-group
            = form.label :address
            = form.text_field :address, id: :profile_address, class: 'form-control'
            = form.error_message_for(:address)
          .form-group
            = form.label :gender_id
            = form.select :gender_id, Gender.all.collect{|f| [f.name, f.id]}, {}, { class: 'form-control', id: :profile_gender_id }
            = form.error_message_for(:gender_id)
        .centered
          = form.submit 'Save', class: 'btn btn-primary'
          = link_to 'Back', :back, class: 'btn btn-info'
  .col-lg-2

app/views/profiles/edit.html.haml
= render 'shared/title', title: 'Editing Profile'
= render 'form', profile: @profile

app/views/profiles/new.html.haml
%h1 New Profile
= render 'form', profile: @profile
= link_to 'Back', profiles_path

app/views/profiles/show.html.haml
= render 'shared/title', title: "Profile of #{@profile.display_name}"
.row
  .col-lg-4
  .col-lg-4
    .media
      .media-left
        - if @profile.image.present?
          = image_tag @profile.image[:large_thumb].url, class: 'media-object img-thumbnail'
        - else
          'No photo'
      .media-body
        %h3.media-heading
          = @profile.full_name
        .table-responsive
          %table.table
            %tbody
              %tr
                %th
                  %span.glyphicon.glyphicon-earphone
                %td
                  %p
                    = @profile.phone
              %tr
                %th
                  %span.glyphicon.glyphicon-user
                %td
                  %p
                    = @profile.gender.name.capitalize
              %tr
                %th
                  %span.glyphicon.glyphicon-time
                %td
                  %p
                    = @profile.dob
              %tr
                %th
                  %span.glyphicon.glyphicon-map-marker
                %td
                  %p
                    = @profile.city_and_country
              %tr
                %th
                  %span.glyphicon.glyphicon-home
                %td
                  %p
                    = @profile.address
    .centered
      = link_to 'Edit Profile', edit_user_profile_path(current_user, @profile ), class: 'btn btn-primary'
      = link_to 'Back', :back, class: 'btn btn-info'
  .col-lg-4