config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :genders
  resources :savings
  resources :incomes
  resources :frequencies
  root to: 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Sidekiq::Web => '/sidekiq'

  get 'search', to: 'search#search'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, path: 'accounts'

  resources :users do
    resources :profiles, only: %i[show edit update]
  end

  resources :budgets do
    resources :expenses
  end
end

app/models/budget.rb
# == Schema Information
#
# Table name: budgets
#
#  id                :integer          not null, primary key
#  title             :string
#  description       :text
#  original_amount   :integer
#  start_date        :date
#  end_date          :date
#  remaining_amount  :integer
#  user_id           :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  extra_used_amount :integer
#
# Indexes
#
#  index_budgets_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Budget < ApplicationRecord
  belongs_to :user
  has_many   :expenses, dependent: :destroy
  after_initialize :init_values

  DEFAULT_DATE_FORMAT = '%d %b %Y'

  attr_reader :total_spent_expense

  ##
  # Customize the pagination's default page value
  #
  self.per_page = 10

  ##
  # Validations
  #
  validates :title, :original_amount, :start_date, :end_date, presence: true
  validates :original_amount, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 2147483647 }
  validate  :is_start_date_greater_than_end_date

  ##
  # Callbacks
  #
  after_update :recalculate_remaining_extra_used_amounts, if: :original_amount_changed?

  ##
  # Elasticsearch 
  #
  searchkick callbacks: :async

  def search_data 
    {
      title: title,
      description: description
    }
  end


  def start_date
    if read_attribute(:start_date) != nil
      read_attribute(:start_date).strftime(DEFAULT_DATE_FORMAT)
    end
  end

  def end_date
    if read_attribute(:end_date) != nil
      read_attribute(:end_date).strftime(DEFAULT_DATE_FORMAT)
    end
  end

  def is_expired?
    if Date.current <= Date.parse(self.end_date)
      false
    elsif Date.current > Date.parse(self.end_date)
      true
    end
  end

  def total_spent_expense
    total_spent_amount  = 0
    expenses            = self.expenses

    if self.expenses.count > 0
      total_spent_amount = expenses.sum(:amount)
    end

    total_spent_amount
  end

  private
    def init_values
      self.original_amount    ||= 0
      self.remaining_amount   ||= 0
      self.extra_used_amount  ||= 0
      self.start_date         ||= Date.current.strftime(DEFAULT_DATE_FORMAT)
      self.end_date           ||= (Date.current + 1.day ).strftime(DEFAULT_DATE_FORMAT)
    end

    def is_start_date_greater_than_end_date
      if Date.parse(start_date) > Date.parse(end_date)
        errors.add(:start_date, %q(can't be greather than end date))
      end
    end

    def recalculate_remaining_extra_used_amounts
      total_spent_amount = total_spent_expense
      
      if total_spent_amount > 0
        original_amount    = self.original_amount
        remaining_amount   = 0
        extra_spent_amount = 0

        if original_amount >= total_spent_amount
          remaining_amount  = original_amount - total_spent_amount
        elsif original_amount < total_spent_amount
          extra_spent_amount = original_amount - total_spent_amount
        end

        self.update_columns(remaining_amount: remaining_amount, extra_used_amount: extra_spent_amount)
      end
    end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_budget, only: %i[show edit update destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = current_user.budgets.paginate(page: params[:page]).order('created_at DESC')
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = current_user.budgets.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = current_user.budgets.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = current_user.budgets.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:title, :description, :original_amount, :start_date, :end_date, :remaining_amount, :extra_used_amount, :user_id)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.haml
= form_for(budget) do |f|
  - if budget.errors.any?
    #error_explanation
      %h3
        = pluralize(budget.errors.count, 'error')
        prohibited from being saved.
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', autofocus: true
    = f.error_message_for(:title)
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .form-group
    = f.label :original_amount
    = f.number_field :original_amount, class: 'form-control', min: 0
    = f.error_message_for(:original_amount)
  .form-group
    = f.label :start_date
    = f.text_field :start_date, class: 'form-control', readonly: true, data: { provide: 'datepicker', date_format: 'dd M yyyy' }
    = f.error_message_for(:start_date)
  .form-group
    = f.label :end_date
    = f.text_field :end_date, class: 'form-control', readonly: true, data: { provide: 'datepicker', date_format: 'dd M yyyy' }
    = f.error_message_for(:end_date)
  .centered
    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Back', :back, class: 'btn btn-info'

app/views/budgets/edit.html.haml
= render 'shared/title', title: 'Editing Budget'
= render 'form', budget: @budget

app/views/budgets/index.html.haml
= render 'shared/title', title: 'Budgets'
%table.table.table-hover
  %thead
    %tr
      %th Title
      %th Start date
      %th End date
      %th Original amount
      %th Used amount
      %th Remaining amount
      %th Extra used amount
      %th{:colspan => "3"}
        %div{:style => "text-align: right;"}
          = link_to 'Add new budget', new_budget_path, target: 'blank', class: 'btn btn-primary'
  %tbody
    - @budgets.each do |budget|
      - class_type = 'default'
      - if budget.is_expired?
        - class_type = 'danger'
      - else
        - class_type = 'success'
      %tr{:class => class_type }
        %td= budget.title.truncate(20)
        %td= budget.start_date
        %td= budget.end_date
        %td= number_with_delimiter(budget.original_amount)
        %td= number_with_delimiter(budget.total_spent_expense)
        %td= number_with_delimiter(budget.remaining_amount)
        %td= number_with_delimiter(budget.extra_used_amount)
        %td
          = link_to 'Add expense',  new_budget_expense_path(budget), class: 'btn btn-primary'
          = link_to 'View expenses', budget_expenses_path(budget), class: 'btn btn-success'
          = link_to 'Show', budget, class: 'btn btn-info'
.centered
  = will_paginate(@budgets, :renderer => WillPaginate::ActionView::LinkRenderer, class: 'pagination-lg')

app/views/budgets/new.html.haml
= render 'shared/title', title: 'New Budget'
= render 'form', budget: @budget

app/views/budgets/show.html.haml
= render 'shared/title', title: "Detail of #{@budget.title}"
%table.table.table-condensed.table-hover.table-responsive
  %tbody
    %tr
      %th Title
      %td= @budget.title
    %tr
      %th Description
      %td= @budget.description
    %tr
      %th Start date
      %td= @budget.start_date
    %tr
      %th End date
      %td= @budget.end_date
    %tr
      %th Original amount
      %td= number_with_delimiter(@budget.original_amount)
    %tr
      %th Remaining amount
      %td= number_with_delimiter(@budget.remaining_amount)
    %tr
      %th Extra used amount
      %td= number_with_delimiter(@budget.extra_used_amount)
    %tr
      %td.centered{:colspan => "2"}
        = link_to 'Edit', edit_budget_path(@budget), class: 'btn btn-warning'
        = link_to 'Destroy', budget_path(@budget), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
        = link_to 'Back', :back, class: 'btn btn-info'
= line_chart @budget.expenses.group_by_day(:spent_date).sum(:amount)