config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :genders
  resources :savings
  resources :incomes
  resources :frequencies
  root to: 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Sidekiq::Web => '/sidekiq'

  get 'search', to: 'search#search'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, path: 'accounts'

  resources :users do
    resources :profiles, only: %i[show edit update]
  end

  resources :budgets do
    resources :expenses
  end
end

app/models/frequency.rb
# == Schema Information
#
# Table name: frequencies
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Frequency < ApplicationRecord
    has_many :incomes
    has_many :savings
end

app/controllers/frequencies_controller.rb
class FrequenciesController < InheritedResources::Base

  private

    def frequency_params
      params.require(:frequency).permit(:name)
    end
end

app/helpers/frequencies_helper.rb
module FrequenciesHelper
end

app/views/frequencies/_form.html.haml
= form_for(frequency) do |f|
  - if frequency.errors.any?
    #error_explanation
      %h2
        = pluralize(frequency.errors.count, "error")
        prohibited this frequency from being saved:
      %ul
        - frequency.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit

app/views/frequencies/edit.html.haml
%h1 Editing Frequency
= render 'form', frequency: @frequency
= link_to 'Show', @frequency
|
= link_to 'Back', frequencies_path

app/views/frequencies/index.html.haml
%p#notice= notice
%h1 Frequencies
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @frequencies.each do |frequency|
      %tr
        %td= frequency.name
        %td= link_to 'Show', frequency
        %td= link_to 'Edit', edit_frequency_path(frequency)
        %td= link_to 'Destroy', frequency, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Frequency', new_frequency_path

app/views/frequencies/new.html.haml
%h1 New Frequency
= render 'form', frequency: @frequency
= link_to 'Back', frequencies_path

app/views/frequencies/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @frequency.name
= link_to 'Edit', edit_frequency_path(@frequency)
|
= link_to 'Back', frequencies_path